"""Module for retrieving information about the standard LSST survey fields.
"""
try:
    # version.py is auto-generated by sconsUtils
    from .version import *  # noqa: F403
except:
    __version__ = "unknown"

from .field import *
from .fields_database import *
from .field_selection import *
